name: flutter_screen_scaling
version: 3.3.2+2
homepage: https://github.com/SunnyFlutter/flutter_screen_scaling
description: A fork of flutter_screenutil with minor changes to the structure
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
